language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev daemontools
install:
  - pip install -r requirements-dev.txt --use-mirrors
before_script:
  - flake8 djangopeople
  - flake8 tests
script:
  - psql -c 'CREATE DATABASE djangopeople;' -U postgres
  - PYTHONPATH=. make test
